# Generated by Django 2.1.2 on 2018-11-01 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': '商品类别表',
                'db_table': '商品类别',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('info', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='categorys')),
                ('num', models.IntegerField(default=0)),
                ('onsale', models.BooleanField(default=True)),
                ('onlinedate', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods')),
            ],
            options={
                'verbose_name_plural': '产品类别',
                'db_table': '产品类别',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='register_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('Verification_problem', models.CharField(max_length=100)),
                ('Verification_answer', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'register_user',
            },
        ),
    ]
